(() => {
  "use strict";
  const KEY="dhplay-data-v1", LEGACY_KEY="hgplay-data-v1";
  const APP_ID="dhplay", OWNER_EMAIL="jedsonpc@hotmail.com", WEB_ACCESS_URL="https://jedsonpc3.github.io/dhplay/", SESSION_IDLE_LIMIT_MS=5*60*1000, SESSION_IDLE_WARNING_MS=60*1000;
  const defaultState={clients:[],plans:[],subscriptions:[],messageHistory:{},settings:{company:"DHPlay",phone:"11 98583-1185",warningDays:5},updatedAt:null};
  let state=loadLocal(), view="dashboard", edit=null, search="", calendarDate=new Date(), supabase=null, session=null, syncTimer=null, deferredInstallPrompt=null, accessUsers=[], accessUsersLoading=false, recoveryMode=false, idleTimer=null, idleCountdown=null, idleWarning=null, lastActivityAt=Date.now();
  const offlineDb=window.createOfflineDatabase?.({dbName:"dhplay-offline-v1"})||null, OUTBOX_KEY="dhplay_state:main";
  const $=s=>document.querySelector(s), money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}), dateBR=v=>v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"—", uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
  const navItems=[['dashboard','▦','Painel'],['clients','♙','Clientes'],['plans','◇','Planos'],['subscriptions','◉','Assinaturas'],['calendar','□','Calendário'],['reports','▤','Relatórios'],['users','♧','Usuários'],['settings','⚙','Gestão']];
  document.addEventListener("DOMContentLoaded",init);
  async function init(){bind(); renderNav(); bindInstall(); await restoreOfflineState(); await initAuth();}
  function bind(){
    $('#loginForm').addEventListener('submit',login); $('#localAccessBtn').onclick=()=>openApp(null);
    $('#togglePasswordBtn').onclick=togglePassword; $('#forgotPasswordBtn').onclick=openPasswordRequest; $('#recoveryForm').addEventListener('submit',submitRecovery); $('#backToLoginBtn').onclick=showLogin;
    $('#logoutBtn').onclick=logout; $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
    $('#qrAccessBtn').onclick=openQrDialog; $('#copyAccessLinkBtn').onclick=copyAccessLink;
    $('#quickAddBtn').onclick=()=>openForm('subscription');
    $('#globalSearch').oninput=e=>{search=e.target.value.toLowerCase(); if(['clients','subscriptions'].includes(view)) render();};
    $('#recordForm').addEventListener('submit',saveForm); $('#importFile').addEventListener('change',importData);
    window.addEventListener('online',()=>flushPending().catch(()=>setSyncBadge('error')));
  }
  async function initAuth(){
    const cfg=window.DHPLAY_SUPABASE||{};
    if(cfg.url&&cfg.anonKey&&window.supabase){supabase=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}); const params=new URLSearchParams(location.search),hash=new URLSearchParams(location.hash.replace(/^#/,''));recoveryMode=['recovery','invite'].includes(params.get('type'))||['recovery','invite'].includes(hash.get('type'));const code=params.get('code');if(code)await supabase.auth.exchangeCodeForSession(code).catch?.(()=>{});const {data}=await supabase.auth.getSession();if(recoveryMode){showRecovery(hash.get('type')==='invite'||params.get('type')==='invite');}else if(data.session)openApp(data.session);supabase.auth.onAuthStateChange((event,s)=>{session=s;if(['PASSWORD_RECOVERY','USER_UPDATED'].includes(event)&&event==='PASSWORD_RECOVERY')showRecovery(false);});}
  }
  async function login(e){e.preventDefault(); const err=$('#loginError'); err.classList.add('hidden'); if(!supabase){err.textContent='Configure o Supabase ou use o acesso local abaixo.';err.classList.remove('hidden');return;} const {data,error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value}); if(error){err.textContent='Não foi possível entrar. Verifique e-mail e senha.';err.classList.remove('hidden');return;}if(!hasDhplayAccess(data.user)){await supabase.auth.signOut({scope:'local'});err.textContent='Este usuário não possui acesso autorizado ao DHPlay.';err.classList.remove('hidden');return;} openApp(data.session);}
  async function openApp(s){session=s;$('#loginScreen').classList.add('hidden');$('#recoveryScreen').classList.add('hidden');$('#appShell').classList.remove('hidden'); if(s)await pullCloud(); await flushPending().catch(()=>{}); setSyncBadge(); render();if(s)startIdleSupervision();}
  async function logout(){clearIdleSupervision();if(supabase&&session)await supabase.auth.signOut({scope:'local'});session=null;$('#appShell').classList.add('hidden');showLogin();}
  function hasDhplayAccess(user){if(!user)return false;if(String(user.email||'').toLowerCase()===OWNER_EMAIL)return true;return user.app_metadata?.app_access?.[APP_ID]?.active===true;}
  function isAdmin(){const user=session?.user;if(!user)return false;if(String(user.email||'').toLowerCase()===OWNER_EMAIL)return true;return ['admin','administrador','owner','proprietario'].includes(String(user.app_metadata?.app_access?.[APP_ID]?.role||'').toLowerCase());}
  function togglePassword(){const input=$('#loginPassword'),visible=input.type==='text';input.type=visible?'password':'text';$('#togglePasswordBtn').textContent=visible?'Exibir':'Ocultar';}
  function showLogin(){recoveryMode=false;$('#recoveryScreen').classList.add('hidden');$('#appShell').classList.add('hidden');$('#loginScreen').classList.remove('hidden');history.replaceState({},'',location.pathname);}
  function showRecovery(invite=false){recoveryMode=true;$('#loginScreen').classList.add('hidden');$('#appShell').classList.add('hidden');$('#recoveryScreen').classList.remove('hidden');$('#recoveryEmailFields').classList.add('hidden');$('#recoveryPasswordFields').classList.remove('hidden');$('#recoveryTitle').textContent=invite?'Ativar seu acesso':'Redefinir senha';$('#recoverySubtitle').textContent='Informe e confirme sua nova senha.';$('#recoverySubmitBtn').textContent='Salvar nova senha';}
  function openPasswordRequest(){$('#loginScreen').classList.add('hidden');$('#recoveryScreen').classList.remove('hidden');$('#recoveryEmailFields').classList.remove('hidden');$('#recoveryPasswordFields').classList.add('hidden');$('#recoveryTitle').textContent='Recuperar senha';$('#recoverySubtitle').textContent='Enviaremos um link seguro para você criar uma nova senha.';$('#recoveryEmail').value=$('#loginEmail').value;$('#recoverySubmitBtn').textContent='Enviar link de redefinição';recoveryMode=false;}
  async function submitRecovery(e){e.preventDefault();const err=$('#recoveryError');err.classList.add('hidden');if(!supabase){err.textContent='Supabase indisponível.';err.classList.remove('hidden');return;}try{if(!recoveryMode){const email=$('#recoveryEmail').value.trim();if(!email)throw new Error('Informe o e-mail.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:new URL('?type=recovery',WEB_ACCESS_URL).href});if(error)throw error;toast('Link de redefinição enviado. Verifique seu e-mail.');showLogin();return;}const password=$('#newPassword').value;if(password.length<8)throw new Error('A senha deve ter pelo menos 8 caracteres.');if(password!==$('#confirmPassword').value)throw new Error('As senhas não coincidem.');const {error}=await supabase.auth.updateUser({password});if(error)throw error;toast('Senha definida com sucesso. Entre novamente.');await supabase.auth.signOut({scope:'local'});showLogin();}catch(error){err.textContent=error.message||'Não foi possível atualizar a senha.';err.classList.remove('hidden');}}
  function accessUrl(){return WEB_ACCESS_URL;}
  function openQrDialog(){const url=accessUrl();$('#qrImage').src=`https://api.qrserver.com/v1/create-qr-code/?size=320x320&data=${encodeURIComponent(url)}`;$('#qrAccessLink').textContent=url;$('#openAccessLinkBtn').href=url;$('#qrDialog').showModal();}
  async function copyAccessLink(){await navigator.clipboard.writeText(accessUrl());toast('Link de acesso copiado.');}
  function renderNav(){$('#nav').innerHTML=navItems.map(([id,icon,label])=>`<button data-view="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');$('#nav').onclick=e=>{const b=e.target.closest('button');if(!b)return;view=b.dataset.view;$('#sidebar').classList.remove('open');renderNav();render();}; $('#nav').querySelector(`[data-view="${view}"]`)?.classList.add('active');}
  function render(){renderNav();const meta={dashboard:['Visão geral','Painel'],clients:['Relacionamento','Clientes'],plans:['Catálogo','Planos'],subscriptions:['Controle comercial','Assinaturas'],calendar:['Vencimentos','Calendário'],reports:['Análise gerencial','Relatórios'],users:['Acesso e segurança','Usuários'],settings:['Dados e nuvem','Gestão']}[view];$('#pageEyebrow').textContent=meta[0];$('#pageTitle').textContent=meta[1]; const f={dashboard:dashboard,clients:clients,plans:plans,subscriptions:subscriptions,calendar:calendar,reports:reports,users:usersView,settings:settings}[view];$('#content').innerHTML=f(); bindView();bindReports();}
  const statusOf=s=>{const end=new Date(s.endDate+'T23:59:59'),today=new Date(),days=Math.ceil((end-today)/86400000);if(s.status==='cancelled')return['Cancelada','expired'];if(days<0)return['Vencida','expired'];if(days<=Number(state.settings.warningDays||5))return[`Vence em ${Math.max(0,days)}d`,'warning'];return['Ativa','active'];};
  function dashboard(){const active=state.subscriptions.filter(s=>statusOf(s)[1]!=='expired'),revenue=active.reduce((a,s)=>a+Number(s.price||0),0),expiring=state.subscriptions.filter(s=>statusOf(s)[1]==='warning').length,expired=state.subscriptions.filter(s=>statusOf(s)[1]==='expired').length;const recent=[...state.subscriptions].sort((a,b)=>a.endDate.localeCompare(b.endDate)).slice(0,6);return `<div class="metrics"><div class="metric"><small>Clientes</small><strong>${state.clients.length}</strong><em>${active.length} assinaturas ativas</em></div><div class="metric" style="--accent:rgba(38,209,149,.2)"><small>Receita recorrente</small><strong>${money(revenue)}</strong><em>estimativa mensal</em></div><div class="metric" style="--accent:rgba(255,207,36,.2)"><small>A vencer</small><strong>${expiring}</strong><em>nos próximos ${state.settings.warningDays} dias</em></div><div class="metric" style="--accent:rgba(255,99,120,.2)"><small>Vencidas</small><strong>${expired}</strong><em>pedem atenção</em></div></div>${renewalMessages()}<div class="grid-2"><article class="card"><div class="card-head"><h2>Próximos vencimentos</h2><button class="ghost-button" data-go="calendar">Ver calendário</button></div>${recentTable(recent)}</article><article class="card"><div class="card-head"><h2>Planos mais usados</h2><button class="ghost-button" data-add="plan">+ Plano</button></div><div class="list">${planSummary()}</div></article></div>`;}
  function localIso(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
  function dayDifference(endDate,today=localIso()){return Math.round((new Date(endDate+'T12:00:00')-new Date(today+'T12:00:00'))/86400000);}
  function hasRenewal(subscription){return state.subscriptions.some(other=>other.id!==subscription.id&&other.clientId===subscription.clientId&&other.planId===subscription.planId&&other.status!=='cancelled'&&String(other.startDate||'')>String(subscription.endDate||''));}
  function dueMessages(today=localIso()){const stages={5:'before',0:'due','-1':'after'};return state.subscriptions.filter(s=>s.status!=='cancelled'&&!hasRenewal(s)&&stages[dayDifference(s.endDate,today)]).map(s=>({subscription:s,client:find('clients',s.clientId),plan:find('plans',s.planId),stage:stages[dayDifference(s.endDate,today)]})).filter(x=>x.client&&x.plan);}
  function renewalText(item){const name=String(item.client.name||'').trim().split(/\s+/)[0]||'cliente',service=item.plan.name,date=dateBR(item.subscription.endDate),smile='\u263A\uFE0F',heart='\u2764\uFE0F';const texts={before:`Olá, ${name}! ${smile}\nAgradecemos por confiar em nossos serviços! Passando para lembrar que sua assinatura de ${service} vencerá em 5 dias, no dia ${date}.\nPara continuar aproveitando o serviço sem interrupções, você já pode solicitar a renovação.\nCaso queira renovar ou tenha alguma dúvida, estamos à disposição. Será um prazer continuar atendendo você! ${heart}`,due:`Olá, ${name}! ${smile}\nPassando para lembrar que sua assinatura de ${service} vence hoje, dia ${date}.\nPara continuar aproveitando o serviço sem interrupções, solicite a renovação ainda hoje.\nAgradecemos pela confiança e permanecemos à disposição! ${heart}`,after:`Olá, ${name}! ${smile}\nIdentificamos que sua assinatura de ${service} venceu no dia ${date}.\nCaso queira continuar utilizando o serviço, entre em contato conosco para realizar a renovação. Será um prazer continuar atendendo você!\nSe você já realizou o pagamento ou solicitou a renovação, por favor, desconsidere esta mensagem. Agradecemos pela confiança! ${heart}`};const company=String(state.settings.company||'').trim(),phone=String(state.settings.phone||'').trim(),signature=[company,phone].filter(Boolean).join(' · ');return texts[item.stage]+(signature?`\n\n${signature}`:'');}
  function whatsappPhone(value){let digits=String(value||'').replace(/\D/g,'');if((digits.length===10||digits.length===11)&&!digits.startsWith('55'))digits='55'+digits;return digits;}
  function messageKey(item){return `${item.subscription.id}:${item.subscription.endDate}:${item.stage}`;}
  function renewalMessages(){const items=dueMessages(),labels={before:'Faltam 5 dias',due:'Vence hoje',after:'Venceu ontem'};return `<section class="card renewal-messages"><div class="card-head"><div><p class="eyebrow">WhatsApp</p><h2>Mensagens de renovação</h2></div><span class="badge ${items.length?'warning':'active'}">${items.length} para hoje</span></div>${items.length?`<div class="renewal-list">${items.map(item=>{const sent=state.messageHistory?.[messageKey(item)],phone=whatsappPhone(item.client.phone);return `<article class="renewal-item"><div><span class="badge warning">${labels[item.stage]}</span><strong>${esc(item.client.name)}</strong><small>${esc(item.plan.name)} · ${dateBR(item.subscription.endDate)} · ${esc(item.client.phone||'Sem WhatsApp')}</small>${sent?`<em>WhatsApp aberto em ${new Date(sent).toLocaleString('pt-BR')}</em>`:''}</div><button class="primary-button" data-whatsapp="${esc(item.subscription.id)}" data-stage="${item.stage}" ${phone.length<12?'disabled title="Cadastre um WhatsApp válido para o cliente"':''}>${sent?'Abrir novamente':'Enviar mensagem'}</button></article>`}).join('')}</div>`:'<p class="muted">Nenhuma mensagem programada para hoje. Os avisos aparecem 5 dias antes, no vencimento e 1 dia depois.</p>'}</section>`;}
  function sendRenewalMessage(subscriptionId,stage){const item=dueMessages().find(x=>x.subscription.id===subscriptionId&&x.stage===stage);if(!item)return toast('Esta mensagem não está mais pendente.');const phone=whatsappPhone(item.client.phone);if(phone.length<12)return toast('Cadastre um WhatsApp válido para o cliente.');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(renewalText(item))}`,'_blank','noopener');state.messageHistory={...(state.messageHistory||{}),[messageKey(item)]:new Date().toISOString()};persist();render();}
  function recentTable(rows){if(!rows.length)return empty('◉','Nenhuma assinatura cadastrada','Cadastre a primeira assinatura para acompanhar os vencimentos.');return `<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Plano</th><th>Vencimento</th><th>Status</th></tr></thead><tbody>${rows.map(s=>{const c=find('clients',s.clientId),p=find('plans',s.planId),st=statusOf(s);return `<tr><td>${esc(c?.name||'Cliente removido')}</td><td>${esc(p?.name||'Plano removido')}</td><td>${dateBR(s.endDate)}</td><td><span class="badge ${st[1]}">${st[0]}</span></td></tr>`}).join('')}</tbody></table></div>`;}
  function planSummary(){if(!state.plans.length)return empty('◇','Sem planos','Cadastre seus planos disponíveis.');return state.plans.map(p=>{const n=state.subscriptions.filter(s=>s.planId===p.id&&statusOf(s)[1]!=='expired').length,max=Math.max(1,state.subscriptions.length);return `<div class="list-item"><div><strong>${esc(p.name)}</strong><small>${money(p.price)} · ${p.duration} dias</small><div class="progress"><span style="width:${n/max*100}%"></span></div></div><span class="badge active">${n} ativos</span></div>`}).join('');}
  function clients(){let rows=state.clients.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(search));return `<div class="section-head"><div><h2>Base de clientes</h2><p class="muted">${rows.length} cliente(s) encontrado(s)</p></div><button class="primary-button" data-add="client">+ Novo cliente</button></div>${rows.length?`<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Nome</th><th>Telefone</th><th>E-mail</th><th>Assinaturas</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td data-label="Nome"><strong>${esc(c.name)}</strong></td><td data-label="Telefone">${esc(c.phone)}</td><td data-label="E-mail">${esc(c.email||'—')}</td><td data-label="Assinaturas">${state.subscriptions.filter(s=>s.clientId===c.id).length}</td><td data-label="Ações">${actions('client',c.id)}</td></tr>`).join('')}</tbody></table></div>`:empty('♙','Nenhum cliente','Use “Novo cliente” para começar sua base.')}`;}
  function plans(){return `<div class="section-head"><div><h2>Planos oferecidos</h2><p class="muted">Defina preço e duração de cada opção.</p></div><button class="primary-button" data-add="plan">+ Novo plano</button></div>${state.plans.length?`<div class="settings-grid">${state.plans.map(p=>`<article class="card"><div class="card-head"><div><span class="badge active">${p.duration} dias</span><h2 style="margin-top:12px">${esc(p.name)}</h2></div>${actions('plan',p.id)}</div><strong style="font-size:1.7rem">${money(p.price)}</strong><p class="muted">${esc(p.description||'Plano de streaming DHPlay')}</p><small>${state.subscriptions.filter(s=>s.planId===p.id).length} assinatura(s)</small></article>`).join('')}</div>`:empty('◇','Nenhum plano','Cadastre os planos que a DHPlay oferece.')}`;}
  function subscriptions(){let rows=state.subscriptions.filter(s=>{const c=find('clients',s.clientId),p=find('plans',s.planId);return ((c?.name||'')+' '+(c?.phone||'')+' '+(p?.name||'')).toLowerCase().includes(search)});return `<div class="section-head"><div><h2>Assinaturas</h2><p class="muted">Acompanhe início, vencimento, valor e situação.</p></div><button class="primary-button" data-add="subscription">+ Nova assinatura</button></div>${rows.length?`<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Cliente</th><th>Plano</th><th>Período</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(s=>{const c=find('clients',s.clientId),p=find('plans',s.planId),st=statusOf(s);return `<tr><td data-label="Cliente"><strong>${esc(c?.name||'Cliente removido')}</strong><br><small class="muted">${esc(c?.phone||'')}</small></td><td data-label="Plano">${esc(p?.name||'Plano removido')}</td><td data-label="Período">${dateBR(s.startDate)} → ${dateBR(s.endDate)}</td><td data-label="Valor">${money(s.price)}</td><td data-label="Status"><span class="badge ${st[1]}">${st[0]}</span></td><td data-label="Ações">${actions('subscription',s.id)}</td></tr>`}).join('')}</tbody></table></div>`:empty('◉','Nenhuma assinatura','Vincule um cliente a um plano e acompanhe o vencimento.')}`;}
  function calendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10),events=state.subscriptions.filter(s=>s.endDate===iso);cells.push(`<div class="day ${d.getMonth()!==m?'outside':''} ${new Date().toDateString()===d.toDateString()?'today':''}"><span class="day-number">${d.getDate()}</span>${events.map(s=>`<span class="calendar-event ${statusOf(s)[1]}">${esc(find('clients',s.clientId)?.name||'Cliente')}</span>`).join('')}</div>`)}return `<div class="section-head"><div><h2>Calendário de vencimentos</h2><p class="muted">Antecipe renovações e evite interrupções.</p></div><div class="calendar-controls"><button class="ghost-button" data-month="-1">‹</button><strong>${calendarDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button class="ghost-button" data-month="1">›</button></div></div><div class="card"><div class="calendar-grid">${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=>`<div class="calendar-label">${x}</div>`).join('')}${cells.join('')}</div></div>`;}
  function reports(){
    const now=new Date(),first=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,last=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10);
    const start=state.settings.reportStart||first,end=state.settings.reportEnd||last,planId=state.settings.reportPlan||'',filterStatus=state.settings.reportStatus||'all';
    const rows=state.subscriptions.filter(s=>String(s.startDate||'')<=end&&String(s.endDate||'')>=start).filter(s=>!planId||s.planId===planId).filter(s=>filterStatus==='all'||reportStatus(s)===filterStatus);
    const revenue=rows.reduce((sum,s)=>sum+Number(s.price||0),0),active=rows.filter(s=>reportStatus(s)==='active').length,warning=rows.filter(s=>reportStatus(s)==='warning').length,expired=rows.filter(s=>reportStatus(s)==='expired').length,cancelled=rows.filter(s=>reportStatus(s)==='cancelled').length,ticket=rows.length?revenue/rows.length:0;
    const planStats=state.plans.map(p=>({name:p.name,count:rows.filter(s=>s.planId===p.id).length,revenue:rows.filter(s=>s.planId===p.id).reduce((a,s)=>a+Number(s.price||0),0)})).filter(x=>x.count).sort((a,b)=>b.count-a.count);
    const months=reportMonths(start,end),monthStats=months.map(m=>({label:new Date(m+'-02T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}),value:rows.filter(s=>String(s.startDate||'').startsWith(m)).reduce((a,s)=>a+Number(s.price||0),0)})),max=Math.max(1,...monthStats.map(x=>x.value));
    return `<div class="reports-page"><section class="card report-filters"><div class="card-head"><div><p class="eyebrow">Período e escopo</p><h2>Acompanhamento de assinaturas</h2></div><div class="report-actions"><button class="ghost-button" id="reportCurrentMonth">Mês atual</button><button class="ghost-button" id="reportCsv">Exportar CSV</button><button class="primary-button" id="reportPrint">Imprimir / PDF</button></div></div><div class="report-filter-grid"><label>Data inicial<input id="reportStart" type="date" value="${start}"></label><label>Data final<input id="reportEnd" type="date" value="${end}"></label><label>Plano<select id="reportPlan"><option value="">Todos os planos</option>${state.plans.map(p=>`<option value="${p.id}" ${planId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Situação<select id="reportStatus"><option value="all">Todas</option>${[['active','Ativas'],['warning','Próximas do vencimento'],['expired','Vencidas'],['cancelled','Canceladas']].map(([v,l])=>`<option value="${v}" ${filterStatus===v?'selected':''}>${l}</option>`).join('')}</select></label></div>${start>end?'<p class="form-error">A data final precisa ser igual ou posterior à data inicial.</p>':''}</section>
    <div class="metrics report-metrics"><div class="metric"><small>Assinaturas</small><strong>${rows.length}</strong><em>${active} ativas no período</em></div><div class="metric" style="--accent:rgba(38,209,149,.2)"><small>Valor contratado</small><strong>${money(revenue)}</strong><em>ticket médio ${money(ticket)}</em></div><div class="metric" style="--accent:rgba(255,207,36,.2)"><small>A vencer</small><strong>${warning}</strong><em>pedem acompanhamento</em></div><div class="metric" style="--accent:rgba(255,99,120,.2)"><small>Vencidas / canceladas</small><strong>${expired+cancelled}</strong><em>${expired} vencidas · ${cancelled} canceladas</em></div></div>
    <div class="grid-2 report-charts"><article class="card"><div class="card-head"><h2>Receita por início de assinatura</h2><span class="muted">${dateBR(start)} a ${dateBR(end)}</span></div>${monthStats.length?`<div class="bar-chart">${monthStats.map(x=>`<div class="bar-column" title="${esc(x.label)}: ${money(x.value)}"><strong>${x.value?money(x.value):''}</strong><div><i style="height:${Math.max(x.value?8:0,x.value/max*100)}%"></i></div><small>${esc(x.label)}</small></div>`).join('')}</div>`:empty('▥','Sem dados','Nenhuma competência no período.')}</article><article class="card"><div class="card-head"><h2>Desempenho por plano</h2><span class="muted">participação no período</span></div><div class="list">${planStats.length?planStats.map(x=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><small>${x.count} assinatura(s) · ${money(x.revenue)}</small><div class="progress"><span style="width:${rows.length?x.count/rows.length*100:0}%"></span></div></div><span class="badge active">${Math.round(x.count/rows.length*100)}%</span></div>`).join(''):empty('◇','Sem movimentação','Nenhum plano encontrado para os filtros.')}</div></article></div>
    <section class="card report-detail"><div class="card-head"><div><p class="eyebrow">Detalhamento</p><h2>Assinaturas encontradas</h2></div><span class="badge active">${rows.length} registro(s)</span></div>${rows.length?`<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Cliente</th><th>Plano</th><th>Período</th><th>Valor</th><th>Situação</th></tr></thead><tbody>${rows.sort((a,b)=>String(a.endDate).localeCompare(String(b.endDate))).map(s=>{const c=find('clients',s.clientId),p=find('plans',s.planId),status=reportStatus(s),labels={active:'Ativa',warning:'A vencer',expired:'Vencida',cancelled:'Cancelada'};return `<tr><td data-label="Cliente"><strong>${esc(c?.name||'Cliente removido')}</strong><br><small class="muted">${esc(c?.phone||'')}</small></td><td data-label="Plano">${esc(p?.name||'Plano removido')}</td><td data-label="Período">${dateBR(s.startDate)} → ${dateBR(s.endDate)}</td><td data-label="Valor">${money(s.price)}</td><td data-label="Situação"><span class="badge ${status==='active'?'active':status==='warning'?'warning':'expired'}">${labels[status]}</span></td></tr>`}).join('')}</tbody></table></div>`:empty('▤','Nenhum resultado','Ajuste os filtros ou cadastre novas assinaturas.')}</section></div>`;
  }
  function reportStatus(s){if(s.status==='cancelled')return'cancelled';return statusOf(s)[1]==='active'?'active':statusOf(s)[1]==='warning'?'warning':'expired';}
  function reportMonths(start,end){if(!start||!end||start>end)return[];const out=[],cursor=new Date(start.slice(0,7)+'-01T12:00:00'),limit=new Date(end.slice(0,7)+'-01T12:00:00');while(cursor<=limit&&out.length<36){out.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}`);cursor.setMonth(cursor.getMonth()+1);}return out;}
  function bindReports(){[['reportStart','reportStart'],['reportEnd','reportEnd'],['reportPlan','reportPlan'],['reportStatus','reportStatus']].forEach(([id,key])=>{if($('#'+id))$('#'+id).onchange=e=>{state.settings[key]=e.target.value;persist();render();};});if($('#reportCurrentMonth'))$('#reportCurrentMonth').onclick=()=>{const now=new Date();state.settings.reportStart=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;state.settings.reportEnd=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10);state.settings.reportPlan='';state.settings.reportStatus='all';persist();render();};if($('#reportPrint'))$('#reportPrint').onclick=()=>window.print();if($('#reportCsv'))$('#reportCsv').onclick=exportReportCsv;}
  function exportReportCsv(){const start=state.settings.reportStart||'',end=state.settings.reportEnd||'',planId=state.settings.reportPlan||'',filterStatus=state.settings.reportStatus||'all',labels={active:'Ativa',warning:'A vencer',expired:'Vencida',cancelled:'Cancelada'};const rows=state.subscriptions.filter(s=>(!start||String(s.startDate||'')<=end)&&(!end||String(s.endDate||'')>=start)).filter(s=>!planId||s.planId===planId).filter(s=>filterStatus==='all'||reportStatus(s)===filterStatus);const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=['Cliente;Telefone;Plano;Data inicial;Data final;Valor;Situação',...rows.map(s=>{const c=find('clients',s.clientId),p=find('plans',s.planId);return [c?.name,c?.phone,p?.name,s.startDate,s.endDate,Number(s.price||0).toFixed(2).replace('.',','),labels[reportStatus(s)]].map(quote).join(';')})].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`dhplay-relatorio-${start||'inicio'}-${end||'fim'}.csv`;a.click();URL.revokeObjectURL(a.href);}
  function usersView(){if(!session)return `<article class="card"><h2>Usuários</h2><p class="muted">Entre pela nuvem para supervisionar os acessos.</p></article>`;if(!isAdmin())return `<article class="card"><h2>Usuários</h2><p class="muted">Somente administradores podem convidar e supervisionar usuários.</p></article>`;queueMicrotask(()=>loadAccessUsers());return `<div class="user-admin-grid"><form id="accessForm" class="card stack"><div><p class="eyebrow">Acesso</p><h2>Convidar usuário</h2></div><label>Nome<input name="name" required autocomplete="off"></label><label>E-mail<input name="email" type="email" required autocomplete="off"></label><label>Perfil<select name="role"><option value="consulta">Consulta</option><option value="operacional" selected>Operacional</option><option value="financeiro">Financeiro</option><option value="admin">Administrador</option></select></label><button class="primary-button" type="submit">Cadastrar e enviar convite</button><p id="accessStatus" class="access-status">O usuário receberá um e-mail para definir a própria senha.</p></form><section class="card"><div class="card-head"><div><p class="eyebrow">Supervisão de login</p><h2>Usuários autorizados</h2></div><button id="refreshUsersBtn" class="ghost-button" type="button">Atualizar</button></div><div id="accessUsers">${renderAccessUsers()}</div></section></div>`;}
  function renderAccessUsers(){if(accessUsersLoading&&!accessUsers.length)return empty('◌','Carregando usuários','Consultando acessos no Supabase.');if(!accessUsers.length)return empty('♧','Nenhum usuário','Envie o primeiro convite para começar.');const current=session?.user?.id;return `<div class="table-wrap access-users-wrap"><table class="access-users-table"><thead><tr><th>Usuário</th><th>Credencial</th><th>Perfil</th><th>Último acesso</th><th>Status</th></tr></thead><tbody>${accessUsers.map(u=>{const email=String(u.email||''),rawName=String(u.name||'').trim(),name=rawName&&rawName.toLowerCase()!==email.toLowerCase()?rawName:(u.role==='admin'?'Administrador principal':'Usuário autorizado');return `<tr><td data-label="Usuário"><strong>${esc(name)}</strong></td><td data-label="Credencial" title="${esc(email)}">${esc(email)}</td><td data-label="Perfil">${esc(roleLabel(u.role))}</td><td data-label="Último acesso">${u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString('pt-BR'):'Nunca acessou'}</td><td data-label="Status"><span class="badge ${u.active?'active':'expired'}">${u.user_id===current?'Usuário atual':u.active?'Ativo':'Inativo'}</span></td></tr>`}).join('')}</tbody></table></div>`;}
  function roleLabel(role){return({admin:'Administrador',operacional:'Operacional',financeiro:'Financeiro',consulta:'Consulta'})[role]||role||'Consulta';}
  async function invokeUserManagement(action,payload={}){if(!supabase||!session)throw new Error('Entre no Supabase antes de gerenciar usuários.');const {data,error}=await supabase.functions.invoke('manage-users',{body:{action,appId:APP_ID,...payload}});if(error)throw new Error(error.message||'Falha na função de usuários.');if(data?.error)throw new Error(data.error);return data||{};}
  async function loadAccessUsers(force=false){if(!isAdmin()||accessUsersLoading||(!force&&accessUsers.length))return;accessUsersLoading=true;try{const result=await invokeUserManagement('list');accessUsers=result.users||[];}catch(error){toast(error.message||'Não foi possível carregar os usuários.');}finally{accessUsersLoading=false;const target=$('#accessUsers');if(target)target.innerHTML=renderAccessUsers();}}
  async function inviteAccessUser(form){const status=$('#accessStatus'),button=form.querySelector('button[type=submit]'),values=Object.fromEntries(new FormData(form));button.disabled=true;status.textContent='Enviando convite com segurança…';try{const result=await invokeUserManagement('invite',{...values,redirectTo:new URL('?type=invite',WEB_ACCESS_URL).href});if(result.existing){const {error}=await supabase.auth.resetPasswordForEmail(values.email,{redirectTo:new URL('?type=recovery',WEB_ACCESS_URL).href});if(error)throw error;}form.reset();accessUsers=[];await loadAccessUsers(true);status.textContent=result.existing?'Usuário já cadastrado. Um link para definir a senha foi enviado.':'Convite enviado. O usuário definirá a própria senha pelo e-mail.';}catch(error){status.textContent=`Não foi possível enviar o convite: ${error.message||error}`;}finally{button.disabled=false;}}
  function settings(){return `<div class="settings-grid"><article class="card"><h2>Dados da operação</h2><form id="settingsForm" class="stack"><label>Nome da empresa<input name="company" value="${esc(state.settings.company)}"></label><label>Telefone de contato<input name="phone" value="${esc(state.settings.phone)}"></label><label>Avisar vencimentos com antecedência<input name="warningDays" type="number" min="1" max="60" value="${state.settings.warningDays}"></label><button class="primary-button">Salvar configurações</button></form></article><article class="card"><h2>Backup e segurança</h2><p class="muted">Exporte uma cópia antes de alterações importantes.</p><div class="stack"><button class="ghost-button" id="exportBtn">Baixar backup JSON</button><button class="ghost-button" id="importBtn">Importar backup</button><button class="ghost-button" id="syncBtn" ${!session?'disabled':''}>Sincronizar agora</button></div><p class="muted"><small>Última atualização: ${state.updatedAt?new Date(state.updatedAt).toLocaleString('pt-BR'):'ainda não sincronizado'}.</small></p></article></div>`;}
  function bindView(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openForm(b.dataset.add));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(b.dataset.edit,b.dataset.id));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete,b.dataset.id));document.querySelectorAll('[data-whatsapp]').forEach(b=>b.onclick=()=>sendRenewalMessage(b.dataset.whatsapp,b.dataset.stage));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render();});document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+Number(b.dataset.month));render();});if($('#settingsForm'))$('#settingsForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.settings={...state.settings,...d,warningDays:Number(d.warningDays)};persist();toast('Configurações salvas.');render();};if($('#accessForm'))$('#accessForm').onsubmit=e=>{e.preventDefault();inviteAccessUser(e.currentTarget);};if($('#refreshUsersBtn'))$('#refreshUsersBtn').onclick=()=>{accessUsers=[];loadAccessUsers(true);};if($('#exportBtn'))$('#exportBtn').onclick=exportData;if($('#importBtn'))$('#importBtn').onclick=()=>$('#importFile').click();if($('#syncBtn'))$('#syncBtn').onclick=()=>pushCloud(true);}
  function actions(type,id){return `<div class="row-actions"><button data-edit="${type}" data-id="${id}" aria-label="Editar">✎</button><button data-delete="${type}" data-id="${id}" aria-label="Excluir">⌫</button></div>`;}
  function empty(icon,title,text){return `<div class="empty"><span>${icon}</span><strong>${title}</strong><p>${text}</p></div>`;}
  function find(bucket,id){return state[bucket].find(x=>x.id===id)}
  function openForm(type,id=null){edit={type,id};const data=id?find(type+'s',id):{};const defs={client:{title:id?'Editar cliente':'Novo cliente',fields:[['name','Nome completo','text',true],['phone','Telefone / WhatsApp','tel',true],['email','E-mail','email'],['notes','Observações','textarea']]},plan:{title:id?'Editar plano':'Novo plano',fields:[['name','Nome do plano','text',true],['price','Valor (R$)','number',true],['duration','Duração do plano (dias)','number',true],['description','Descrição','textarea']]},subscription:{title:id?'Editar assinatura':'Nova assinatura',fields:[['clientId','Cliente','client',true],['planId','Plano','plan',true],['startDate','Data inicial','date',true],['endDate','Data final calculada','date',true,'readonly'],['price','Valor cobrado (R$)','number',true],['status','Situação','status'],['notes','Observações','textarea']]}}[type];$('#dialogTitle').textContent=defs.title;$('#formFields').innerHTML=defs.fields.map(f=>field(f,data)).join('');$('#recordDialog').showModal(); if(type==='subscription'){const plan=$('[name=planId]'),start=$('[name=startDate]'),end=$('[name=endDate]'),price=$('[name=price]');const calculateEnd=()=>{const p=find('plans',plan.value);if(!p||!start.value){end.value='';return;}price.value=p.price;const result=new Date(start.value+'T12:00:00');result.setDate(result.getDate()+Math.max(1,Number(p.duration||1))-1);end.value=result.toISOString().slice(0,10);end.title=`Calculado com base em ${p.duration} dia(s) do plano ${p.name}`;};plan.addEventListener('change',calculateEnd);start.addEventListener('change',calculateEnd);if(!id)start.value=new Date().toISOString().slice(0,10);calculateEnd();}}
  function field([name,label,type,required,mode],data){const v=data[name]??'';if(type==='textarea')return `<label class="full">${label}<textarea name="${name}">${esc(v)}</textarea></label>`;if(type==='client'||type==='plan'){const bucket=type==='client'?state.clients:state.plans;return `<label>${label}<select name="${name}" ${required?'required':''}><option value="">Selecione</option>${bucket.map(x=>`<option value="${x.id}" ${v===x.id?'selected':''}>${esc(x.name)}${type==='plan'?` · ${x.duration} dias`:''}</option>`).join('')}</select></label>`;}if(type==='status')return `<label>${label}<select name="status"><option value="active" ${v!=='cancelled'?'selected':''}>Ativa</option><option value="cancelled" ${v==='cancelled'?'selected':''}>Cancelada</option></select></label>`;return `<label>${label}<input name="${name}" type="${type}" value="${esc(v)}" ${type==='number'?'step="0.01" min="0"':''} ${required?'required':''} ${mode==='readonly'?'readonly aria-readonly="true"':''}></label>`;}
  function saveForm(e){e.preventDefault();if(e.submitter?.value==='cancel'){$('#recordDialog').close();return;}const data=Object.fromEntries(new FormData(e.target));if(edit.type==='plan'||edit.type==='subscription')data.price=Number(data.price);if(edit.type==='plan')data.duration=Number(data.duration);const bucket=edit.type+'s';if(edit.id){Object.assign(find(bucket,edit.id),data);}else state[bucket].push({...data,id:uid(),createdAt:new Date().toISOString()});persist();$('#recordDialog').close();toast('Registro salvo com sucesso.');render();}
  function remove(type,id){const labels={client:'este cliente',plan:'este plano',subscription:'esta assinatura'};$('#confirmText').textContent=`Você realmente deseja excluir ${labels[type]}?`;$('#confirmDialog').showModal();$('#confirmDialog').onclose=()=>{if($('#confirmDialog').returnValue!=='confirm')return;state[type+'s']=state[type+'s'].filter(x=>x.id!==id);if(type==='client')state.subscriptions=state.subscriptions.filter(x=>x.clientId!==id);if(type==='plan')state.subscriptions=state.subscriptions.filter(x=>x.planId!==id);persist();render();toast('Registro excluído.');};}
  function persist(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));offlineDb?.putState('main',state,{source:'local'}).catch(()=>{});offlineDb?.enqueue(OUTBOX_KEY,state,{online:navigator.onLine}).catch(()=>{});if(session){clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushCloud(false),800)}setSyncBadge();}
  function mergeState(value={}){return {...structuredClone(defaultState),...value,messageHistory:value.messageHistory||{},settings:{...defaultState.settings,...(value.settings||{})}};}
  function loadLocal(){try{const saved=localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY)||'{}';const parsed=mergeState(JSON.parse(saved));if(!localStorage.getItem(KEY)&&saved!=='{}')localStorage.setItem(KEY,JSON.stringify(parsed));return parsed}catch{return structuredClone(defaultState)}}
  async function restoreOfflineState(){if(!offlineDb)return;const saved=await offlineDb.getState('main').catch(()=>null);if(saved?.value&&String(saved.value.updatedAt||'')>String(state.updatedAt||'')){state=mergeState(saved.value);localStorage.setItem(KEY,JSON.stringify(state));}}
  async function pullCloud(){setSyncBadge('syncing');const cfg=window.DHPLAY_SUPABASE;const {data,error}=await supabase.from(cfg.table).select('data,updated_at').eq('id',cfg.rowId).maybeSingle();if(error){toast('Sem conexão com a nuvem. Usando dados locais.');setSyncBadge('error');return;}const pending=await offlineDb?.getPending(OUTBOX_KEY).catch(()=>null),localCount=dataCount(state),cloudCount=dataCount(data?.data);if(data?.data&&!pending){if(localCount>0&&cloudCount===0){localStorage.setItem(`${KEY}-recovery-${Date.now()}`,JSON.stringify(state));await offlineDb?.enqueue(OUTBOX_KEY,state,{reason:'cloud-empty-protection'}).catch(()=>{});toast('Dados locais preservados: a nuvem estava vazia. Sincronize para enviá-los.');}else{if(localCount>0)localStorage.setItem(`${KEY}-backup-${Date.now()}`,JSON.stringify(state));state=mergeState(data.data);localStorage.setItem(KEY,JSON.stringify(state));await offlineDb?.putState('main',state,{source:'cloud'});}}else if(!data)await pushCloud(false);setSyncBadge();}
  function dataCount(value){return ['clients','plans','subscriptions'].reduce((total,key)=>total+(Array.isArray(value?.[key])?value[key].length:0),0);}
  async function pushCloud(show){if(!supabase||!session)return;if(!navigator.onLine){setSyncBadge('pending');if(show)toast('Sem internet. Alterações guardadas para sincronizar depois.');return;}setSyncBadge('syncing');const cfg=window.DHPLAY_SUPABASE;const snapshot=structuredClone(state);const {error}=await supabase.from(cfg.table).upsert({id:cfg.rowId,user_id:session.user.id,data:snapshot,updated_at:new Date().toISOString()},{onConflict:'id'});if(error){setSyncBadge('error');if(show)toast('Não foi possível sincronizar. As alterações continuam salvas neste aparelho.');return;}const pending=await offlineDb?.getPending(OUTBOX_KEY).catch(()=>null);if(pending?.value&&JSON.stringify(pending.value)===JSON.stringify(snapshot))await offlineDb.removePending(OUTBOX_KEY);setSyncBadge();if(show)toast('Dados sincronizados com a nuvem.');}
  async function flushPending(){if(!session||!navigator.onLine||!offlineDb)return;const pending=await offlineDb.getPending(OUTBOX_KEY);if(!pending?.value)return;state=mergeState(pending.value);await pushCloud(false);}
  function setSyncBadge(mode){const el=$('#syncBadge');if(!session){el.textContent='Local';el.className='status-pill local';return;}el.textContent=mode==='syncing'?'Sincronizando…':mode==='pending'?'Pendente (offline)':mode==='error'?'Salvo localmente':'Nuvem ativa';el.className='status-pill'+(['error','pending'].includes(mode)?' local':'');}
  function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`dhplay-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
  function importData(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.clients||!d.plans||!d.subscriptions)throw 0;state=mergeState(d);persist();render();toast('Backup importado.');}catch{toast('Arquivo de backup inválido.');}};r.readAsText(file);e.target.value='';}
  function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2800)}
  function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function clearIdleSupervision(){clearTimeout(idleTimer);clearInterval(idleCountdown);idleTimer=null;idleCountdown=null;idleWarning?.remove();idleWarning=null;}
  async function closeIdleSession(){clearIdleSupervision();try{await supabase?.auth.signOut({scope:'local'});}catch{}session=null;$('#appShell').classList.add('hidden');showLogin();const err=$('#loginError');err.textContent='Sua sessão foi encerrada por inatividade.';err.classList.remove('hidden');}
  function showIdleWarning(){const deadline=lastActivityAt+SESSION_IDLE_LIMIT_MS;if(Date.now()>=deadline)return closeIdleSession();idleWarning=document.createElement('div');idleWarning.className='idle-session-warning';idleWarning.setAttribute('role','alertdialog');idleWarning.innerHTML='<section><strong>Sessão ociosa</strong><p>Por segurança, o DHPlay será fechado em <b>60 segundos</b>. Toque em qualquer lugar para continuar.</p><button type="button">Continuar no app</button></section>';document.body.appendChild(idleWarning);idleWarning.querySelector('button').onclick=resetIdleSupervision;const count=idleWarning.querySelector('b');idleCountdown=setInterval(()=>{const seconds=Math.max(0,Math.ceil((deadline-Date.now())/1000));count.textContent=`${seconds} segundo${seconds===1?'':'s'}`;if(seconds<=0)closeIdleSession();},250);}
  function resetIdleSupervision(){lastActivityAt=Date.now();clearIdleSupervision();if(session)idleTimer=setTimeout(showIdleWarning,SESSION_IDLE_LIMIT_MS-SESSION_IDLE_WARNING_MS);}
  function resumeIdleSupervision(){clearIdleSupervision();const remaining=lastActivityAt+SESSION_IDLE_LIMIT_MS-Date.now();if(remaining<=0)return closeIdleSession();if(remaining<=SESSION_IDLE_WARNING_MS)return showIdleWarning();idleTimer=setTimeout(showIdleWarning,remaining-SESSION_IDLE_WARNING_MS);}
  function startIdleSupervision(){if(window.__dhplayIdleBound){resetIdleSupervision();return;}window.__dhplayIdleBound=true;['pointerdown','touchstart','keydown','scroll'].forEach(name=>window.addEventListener(name,resetIdleSupervision,{passive:true}));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session)resumeIdleSupervision();});resetIdleSupervision();}
  function bindInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden');};window.addEventListener('appinstalled',()=>toast('DHPlay instalado com sucesso.'));}
})();

